version: '2'
services:
  retro-user-management:
    image: eahedav/retro-user-management:latest
    ports:
      - 3000:3000
    networks:
      main:
        aliases:
          - retro-api
    command: >
      /bin/bash -c "sleep 2; node ."

networks:
  main: