http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  users:
    host: localhost
    paths:
      - /Users
      - /Users/login
  graphql:
    host: '*'
    paths:
      - /graphiql
      - /graphql
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  users:
    url: 'http://localhost:3000/api'
  graphql:
    url: 'http://retro-api:3000'
policies:
  - user-exists
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  users:
    apiEndpoints:
      - users
    policies:
      - cors:
        - action:
            origin: '*'
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
        - action:
            serviceEndpoint: users
            changeOrigin: true
  retro-api-graphql:
    apiEndpoints:
      - graphql
    policies:
      - user-exists:
      - cors:
        - action:
          origin: '*'
          methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
        - action:
            serviceEndpoint: graphql
            changeOrigin: true